version: 1
frontend:
    phases:
        preBuild:
            commands:
                - 'cd frontend'  # Vérifier que le dossier existe
                - 'npm install'
        build:
            commands:
                - 'npm run build'
    artifacts:
        baseDirectory: /frontend/build
        files:
            - '**/*'
